# Generated by Django 3.2.13 on 2022-06-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категорию услуг', 'verbose_name_plural': '1.Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ['id'], 'verbose_name': 'Цены', 'verbose_name_plural': '3.Цены'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Фотоуслуги и сувениры', 'verbose_name_plural': '2.Фотоуслуги и сувениры'},
        ),
        migrations.AddField(
            model_name='prices',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
    ]
