# Generated by Django 3.2.13 on 2022-06-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_auto_20220608_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'ordering': ['id'], 'verbose_name': 'Дополнительную информацию', 'verbose_name_plural': '4.Дополнительная информация'},
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['id'], 'verbose_name': 'контакты и навигацию', 'verbose_name_plural': '5.НЕ трогать'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Объявление', 'verbose_name_plural': '6.Объявление'},
        ),
	 migrations.AddField(
            model_name='extra',
            name='extra_image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение если есть'),
        ),
       
        migrations.AlterField(
            model_name='nav',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='элемент навигации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Объявление'),
        ),
    ]
