# Generated by Django 3.2.14 on 2022-07-27 10:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_auto_20220630_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='gallery_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='ссылка на фотографии'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('gallery_image', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание фотографии')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('galleryLink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart.services', verbose_name='Ссылка на услугу')),
            ],
            options={
                'verbose_name': 'фото в галерею',
                'verbose_name_plural': 'Галерея',
                'ordering': ['id'],
            },
        ),
    ]
